### PR TITLE
Updated onClickEntityLink to onClickContentLink

### PR DESCRIPTION
**Pull request by alessiocali**
The Document API update broke compatibility when clicking on a Scene Journal link. The new function is called `onClickContentLink`. I also updated the way the entity (or rather, the document) is fetched from the game data.

Truth be told I went full code-monkey here and just patched the bare  minimum to make it work, I don't have a lot of familiarity with Foundry's API (which is a kind way to say I have none).

### CODE REVIEW

**Comment by alessiocali** [comment]
It should probably be noted that this breaks compatibility with 0.7.x so it should probably be included in a separate branch for 0.8.x

**Comment by copyosaurus** [comment]
Hi,
I was just looking into fixing this myself. Hopefully @jegasus will find the time to merge this and I can continue using this after the update to 0.8.6.

Thank you :)

**Comment by jegasus** [comment]
@alessiocali : Thank you so so much for taking the initiative and writing this update. I've merged the new version onto the main branch and will release it soon. I've added a special mention to you in the changelog =)

Thanks again for being awesome!

**Comment by alessiocali** [comment]
❤️ You're welcome! I'm not a Javascript expert but I know a thing or two about debugging unknown code, so I love to help when I can 🙂

**Pull request merged**
